# Generated by Django 4.0.5 on 2022-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_watchlist_name_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
