# Generated by Django 4.0.5 on 2022-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_strategy_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='visited',
        ),
        migrations.AddField(
            model_name='strategy',
            name='efficiency',
            field=models.TextField(default='0'),
        ),
    ]
