# Generated by Django 4.0.5 on 2022-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_strategy_visited_strategy_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='efficiency',
            field=models.FloatField(default=0),
        ),
    ]
